### ISSUE TITLE
윈도우에서 gunicorn 실행하려면?

### ISSUE THREAD

**Issue by subin812** [riseryan89/shrinkers#4]
gunicorn --bind 127.0.0.1:8000 shrinkers.wsgi:application

실행 시, 

ModuleNotFoundError: No module named 'fcntl'

에러 발생 합니다.

윈도우 사용자는 어떻게 해야할지 ㅠㅠ

**Comment by riseryan89** [comment]
안녕하세요.

배포는 구니콘을 사용하시되, 윈도우에서 테스트는 waitress를 사용하시면 편리합니다.
gunicorn이 윈도우에서 돌아가지 않습니다.

Waitress 공식 매뉴얼
https://docs.pylonsproject.org/projects/waitress/en/latest/

사용법과 구동법은 구니콘과 대동소이 합니다.

**Comment by riseryan89** [comment]
이슈는 필요시 언제든지 여실수 있습니다!
